# Generated by Django 3.2.10 on 2023-11-24 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='logindb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(blank=True, max_length=100, null=True)),
                ('s_mail', models.CharField(blank=True, max_length=100, null=True)),
                ('s_pass', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
