# Generated by Django 3.2.10 on 2023-12-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0005_auto_20231220_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiverdb',
            name='re_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
