# Generated by Django 3.2.10 on 2023-12-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0007_contactdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiverdb',
            name='s_mail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
