# Generated by Django 3.2.10 on 2023-12-24 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0009_rename_s_mail_receiverdb_us_mail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receiverdb',
            old_name='us_mail',
            new_name='use_mail',
        ),
    ]
