# Generated by Django 3.2.10 on 2023-12-24 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0010_rename_us_mail_receiverdb_use_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiverdb',
            name='use_mail',
        ),
    ]
