# Generated by Django 3.2.10 on 2023-12-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0011_remove_receiverdb_use_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiverdb',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
