# Generated by Django 3.2.10 on 2023-12-25 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0012_receiverdb_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodb',
            name='m_ai',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
