# Generated by Django 3.2.10 on 2023-12-25 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0013_prodb_m_ai'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prodb',
            name='m_ai',
        ),
    ]
